app = "testazon-bot-mgfosg"

[build]
  dockerfile = "Dockerfile"

[env]
  API_TOKEN = "8137004758:AAHaBW6aZwoMTn60rR9gK_FXqJ_69bEydMQ"
  WEBHOOK_URL = "https://testazon-bot-mgfosg.fly.dev/"
  ADMIN_ID = "6014547283"

[[services]]
  internal_port = 5000
  external_port = 80
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    port = "80"
    handlers = ["http"]
